name: Flutter Web Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build and Deploy Web App
    runs-on: ubuntu-latest
    env:
      BASE_HREF: /${{ github.event.repository.name }}/
    steps:
      # Step 1: Checkout Repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter (with a compatible version)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.5'   # Update this version as per your needs
          channel: 'stable'

      # Step 3: Run flutter pub get
      - name: Install Dependencies
        run: flutter pub get
        working-directory: ./WordleClone

      # Step 4: Build Flutter Web
      - name: Build Flutter Web
        run: flutter build web --release --web-renderer html --base-href $BASE_HREF
        working-directory: ./WordleClone

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/master' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./WordleClone/build/web
