name: Flutter Web Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Deploy Web App
    runs-on: ubuntu-latest
    env:
      BASE_HREF: /${{ github.event.repository.name }}/
    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.8.1'
          channel: 'stable'

      # Step 3: Build Flutter web app
      - name: Build Flutter Web
        run: flutter build web --release --web-renderer html --base-href $BASE_HREF

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
